shiqi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: myweb
    username: root
    password: Zhouyi20070102%
  ai:
    api-key: sk-64fcb9d69a284eea8619d4893c851902
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
